export type ResourceDetailRecord = {
  id: string;
  slug: string;
  active: boolean;
  office_or_department: string;
  program_name: string;
  description: string | null;
  category: string | null;
  invite_march_partner_fair: boolean | null;
  partner_fair_attended: string | null;
  recruit_for_grocery_giveaways: boolean | null;
  primary_contact_name: string | null;
  primary_contact_title: string | null;
  primary_contact_email: string | null;
  primary_contact_phone: string | null;
  primary_contact_phone_norm: string | null;
  secondary_contact_name: string | null;
  secondary_contact_title: string | null;
  secondary_contact_email: string | null;
  secondary_contact_phone: string | null;
  secondary_contact_phone_norm: string | null;
  services_select_all: string | null;
  additional_info: string | null;
  tabling_at_events: boolean;
  promotional_materials: boolean;
  educational_workshops: boolean;
  volunteer_recruitment_support: boolean;
  tags: string[] | null;
};
